// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1132FinalProject.Data;

#nullable disable

namespace _1132FinalProject.Migrations
{
    [DbContext(typeof(CmsContext))]
    partial class CmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_1132FinalProject.Models.ContactCommitteesModel", b =>
                {
                    b.Property<int>("CommitteeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommitteeId"));

                    b.Property<string>("IG_Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommitteeId");

                    b.ToTable("Table_s1121768_CommitteeMembers");

                    b.HasData(
                        new
                        {
                            CommitteeId = 1181700,
                            IG_Account = "dancer_pizza",
                            NickName = "Pizza",
                            PhotoUrl = "~/Images/CommitteeCard/Spongebob.png",
                            Position = "教學長",
                            Section = "Locking"
                        },
                        new
                        {
                            CommitteeId = 1181701,
                            IG_Account = "@SquidWard",
                            NickName = "章魚哥",
                            PhotoUrl = "~/Images/CommitteeCard/Squidward.png",
                            Position = "社長",
                            Section = "Locking"
                        },
                        new
                        {
                            CommitteeId = 1181702,
                            IG_Account = "@Sandy",
                            NickName = "珊迪",
                            PhotoUrl = "~/Images/CommitteeCard/Sandy.png",
                            Position = "教學長",
                            Section = "Jazz"
                        },
                        new
                        {
                            CommitteeId = 1181703,
                            IG_Account = "@Patrick",
                            NickName = "派大星",
                            PhotoUrl = "~/Images/CommitteeCard/Patrick.png",
                            Position = "活動長",
                            Section = "Popping"
                        },
                        new
                        {
                            CommitteeId = 1181704,
                            IG_Account = "@Plankton",
                            NickName = "皮老闆",
                            PhotoUrl = "~/Images/CommitteeCard/Plankton.png",
                            Position = "副社長",
                            Section = "Breaking"
                        },
                        new
                        {
                            CommitteeId = 1181705,
                            IG_Account = "@Mr_Krab",
                            NickName = "蟹老闆",
                            PhotoUrl = "~/Images/CommitteeCard/Krab.png",
                            Position = "總務長",
                            Section = "hiphop"
                        });
                });

            modelBuilder.Entity("_1132FinalProject.Models.NewMembersModel", b =>
                {
                    b.Property<string>("StuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IG_Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StuId");

                    b.ToTable("Table_s1121768_NewMembers");

                    b.HasData(
                        new
                        {
                            StuId = "1191700",
                            Department = "資管系",
                            IG_Account = "@Wang_1700",
                            Name = "小王",
                            NickName = "Alex",
                            RegisteredAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Section = "Locking"
                        },
                        new
                        {
                            StuId = "1191701",
                            Department = "資工系",
                            IG_Account = "@Lee_1700",
                            Name = "小李",
                            NickName = "Bob",
                            RegisteredAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Section = "Popping"
                        },
                        new
                        {
                            StuId = "1191702",
                            Department = "企管系",
                            IG_Account = "@Char_1700",
                            Name = "查理",
                            NickName = "Charlie",
                            RegisteredAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Section = "Breaking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
